name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker image
        run: |
          # Convert both the username and repository name to lowercase
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          USERNAME=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${USERNAME}/${REPO_NAME}:latest .

      - name: Push Docker image
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          USERNAME=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${USERNAME}/${REPO_NAME}:latest
