name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          # Convert both GitHub username and repository name to lowercase
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          USERNAME=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')
           docker build -t ghcr.io/${REPO_NAME}:${VERSION} .

      - name: Push Docker image
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          USERNAME=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')
           docker push ghcr.io/${REPO_NAME}:${VERSION} .
